#!/bin/bash

set -e

echo "Installing artillery for load tests: https://artillery.io/docs/getting-started/"

npm install -g artillery

echo "Running artillery load tests..."

artillery quick --duration 10 --rate 10 $APP_URL
