jobs:
- name: unit-tests
  serial: true
  public: true
  plan:
  - get: concourse-pipeline-samples
    trigger: true
  - task: run-unit-tests
    file: concourse-pipeline-samples/blue-green-app-deployment/ci/tasks/unit-tests.yml

- name: load-tests
  serial: true
  public: true
  plan:
  - aggregate:
    - get: load-test-app-manifest
    - get: concourse-pipeline-samples
      trigger: true
      passed: [ unit-tests ]
  - put: cf
    params:
      manifest: load-test-app-manifest/manifest.yml
      path: concourse-pipeline-samples/blue-green-app-deployment/bgd-app
  - task: run-load-tests
    file: concourse-pipeline-samples/blue-green-app-deployment/ci/tasks/load-tests.yml
    params:
      APP_URL: http://load-test-((app-suffix)).((app-domain))
# TODO: delete app after succefull test


- name: deploy-staging
  serial: true
  public: true
  plan:
  - aggregate:
    - get: staging-app-manifest
    - get: concourse-pipeline-samples
      trigger: true
      passed: [ load-tests ]
  - put: cf
    params:
      manifest: staging-app-manifest/manifest.yml
      path: concourse-pipeline-samples/blue-green-app-deployment/bgd-app
      current_app_name: ((app-name))

- name: deploy-prod
  serial: true
  public: true
  plan:
  - aggregate:
    - get: prod-app-manifest
    - get: concourse-pipeline-samples
      trigger: false
      passed: [ deploy-staging ]
  - put: cf
    params:
      manifest: prod-app-manifest/manifest.yml
      path: concourse-pipeline-samples/blue-green-app-deployment/bgd-app
      current_app_name: ((app-suffix))

resources:
- name: concourse-pipeline-samples
  type: git
  source:
    branch: master
    uri: ((git_remote))
- name: load-test-app-manifest
  type: file
  source:
    filename: manifest.yml
    content:
      applications:
      - name: load-test-((app-suffix))
        hostname: load-test-((app-suffix))
- name: staging-app-manifest
  type: file
  source:
    filename: manifest.yml
    content:
      applications:
      - name: staging-((app-suffix))
        hostname: load-test-((app-suffix))
- name: prod-app-manifest
  type: file
  source:
    filename: manifest.yml
    content:
      applications:
      - name: ((app-suffix))
        instances: 2
        hostname: ((app-suffix))
- name: cf
  type: cf
  source:
    api: ((api))
    organization: ((organization))
    username: ((username))
    password: ((password))
    skip_cert_check: true
    current_app_name: ((app-name))
    space: ((space))

resource_types:
- name: file
  type: docker-image
  source:
    repository: aequitas/concourse-file-resource
